export const SET_SHOW_ORBITS = "SET_SHOW_ORBITS";
export const SET_SHOW_LABELS = "SET_SHOW_LABELS";
export const SET_SHOW_BACKGROUND_STARS = "SET_SHOW_BACKGROUND_STARS";
export const SET_SHOW_DEBUG_INFO = "SET_SHOW_DEBUG_INFO";

export const SET_KEEP_CENTERED = "SET_KEEP_CENTERED";
