// Options
export const SET_SHOW_ORBITS = "SET_SHOW_ORBITS";
export const SET_SHOW_LABELS = "SET_SHOW_LABELS";
export const SET_SHOW_BACKGROUND_STARS = "SET_SHOW_BACKGROUND_STARS";
export const SET_REMOVE_ANIMATIONS = "SET_REMOVE_ANIMATIONS";
export const SET_SHOW_DEBUG_INFO = "SET_SHOW_DEBUG_INFO";

// Object info
export const SET_KEEP_CENTERED = "SET_KEEP_CENTERED";
export const SET_SELECTED_OBJECT = "SET_SELECTED_OBJECT";

// Time
export const SET_DISPLAY_TIME = "SET_DISPLAY_TIME";
export const SET_TIME_STEP_INDEX = "SET_TIME_STEP_INDEX";
export const INCREMENT_TIME_STEP_INDEX = "INCREMENT_TIME_STEP_INDEX";
export const DECREMENT_TIME_STEP_INDEX = "DECREMENT_TIME_STEP_INDEX";
export const PAUSE_TIME = "PAUSE_TIME";

// Map
export const SET_SCREEN_CENTER = "SET_SCREEN_CENTER";
export const SET_ZOOM = "SET_ZOOM";

// UI
export const SET_DETAILS_PANE_OPEN = "SET_DETAILS_PANE_OPEN";
export const SET_OPTIONS_PANE_OPEN = "SET_OPTIONS_PANE_OPEN";
export const SET_TOUR_MODAL_OPEN = "SET_TOUR_MODAL_OPEN";
export const ADD_TEXT_BUBBLE = "ADD_TEXT_BUBBLE";
export const REMOVE_TEXT_BUBBLE = "REMOVE_TEXT_BUBBLE";
export const SET_CURRENT_TOUR = "SET_CURRENT_TOUR";
