# Generated by Django 4.0 on 2022-01-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitalBody',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrbitalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('semimajor_axis', models.DecimalField(decimal_places=8, max_digits=18)),
                ('eccentricity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('inclination', models.DecimalField(decimal_places=8, max_digits=18)),
                ('meanLongitude', models.DecimalField(decimal_places=8, max_digits=18)),
                ('longitudeOfPeriapsis', models.DecimalField(decimal_places=8, max_digits=18)),
                ('longitudeOfAscendingNode', models.DecimalField(decimal_places=8, max_digits=18)),
                ('orbital_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizonsapi.orbitalbody')),
            ],
        ),
    ]
