# Generated by Django 4.0 on 2022-01-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizonsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orbitalposition',
            old_name='longitudeOfAscendingNode',
            new_name='longitude_of_ascending_node',
        ),
        migrations.RenameField(
            model_name='orbitalposition',
            old_name='longitudeOfPeriapsis',
            new_name='longitude_of_periapsis',
        ),
        migrations.RenameField(
            model_name='orbitalposition',
            old_name='meanLongitude',
            new_name='mean_longitude',
        ),
    ]
