# Generated by Django 4.0 on 2023-03-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonsapi', '0002_rename_longitudeofascendingnode_orbitalposition_longitude_of_ascending_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitalposition',
            name='center',
            field=models.CharField(default='500@10', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='orbitalposition',
            constraint=models.UniqueConstraint(fields=('orbital_body', 'center', 'time'), name='unique_orbital_position'),
        ),
    ]
